version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestBTProject
  gitServerName: BT
  gitUrl: https://github.com/Bharathi-Thammisetty-IBM
  gitUsername: Bharathi-Thammisetty-IBM
  gitBranch: main
services:
- serviceName: project.testbt.integrations:DB_git
  packages:
  - name: TestBTProject
    version: "1.0"
